import {
	boolean,
	integer,
	jsonb,
	pgEnum,
	pgTable,
	primaryKey,
	text,
	timestamp,
	uuid,
} from "drizzle-orm/pg-core"

export const tierEnum = pgEnum("tier", ["free", "premium"])
export const panelEnum = pgEnum("panel_type", ["3x-ui", "marzban", "static"])
export const serverStatusEnum = pgEnum("server_status", [
	"unknown",
	"online",
	"offline",
])

export const servers = pgTable("servers", {
	id: uuid("id").primaryKey().defaultRandom(),
	name: text("name").notNull(),
	countryCode: text("country_code").notNull(),
	city: text("city"),
	host: text("host").notNull(),
	port: integer("port").notNull().default(443),
	// Node's routed IPv6 prefix (e.g. 2a01:4f8:c17:1234::/64). When set, each
	// device gets its own random address from it.
	ipv6Prefix: text("ipv6_prefix"),
	// Give clients the IPv4 address too (fallback for devices without IPv6).
	// false = IPv6-only: the node's IPv4 is never sent to the app.
	exposeIpv4: boolean("expose_ipv4").notNull().default(true),
	tier: tierEnum("tier").notNull().default("free"),
	enabled: boolean("enabled").notNull().default(true),
	sortOrder: integer("sort_order").notNull().default(0),

	// VLESS + Reality parameters handed to clients
	realityPublicKey: text("reality_public_key").notNull(),
	realityShortId: text("reality_short_id").notNull().default(""),
	realitySni: text("reality_sni").notNull(),
	fingerprint: text("fingerprint").notNull().default("chrome"),
	flow: text("flow").notNull().default("xtls-rprx-vision"),

	// How per-device clients are provisioned on the node
	panelType: panelEnum("panel_type").notNull().default("3x-ui"),
	panelUrl: text("panel_url"),
	panelUsername: text("panel_username"),
	panelPassword: text("panel_password"),
	// 3x-ui 3.x API token; used instead of username/password when set
	panelApiToken: text("panel_api_token"),
	// PEM of the panel's self-signed certificate, pinned for HTTPS to the panel
	panelTlsCert: text("panel_tls_cert"),
	// 3x-ui inbound id, or Marzban inbound tag
	panelInbound: text("panel_inbound"),
	// Used only when panelType = static: one UUID shared by every device
	staticUuid: text("static_uuid"),

	status: serverStatusEnum("status").notNull().default("unknown"),
	latencyMs: integer("latency_ms"),
	lastCheckedAt: timestamp("last_checked_at", { withTimezone: true }),
	lastError: text("last_error"),
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
})

export const devices = pgTable("devices", {
	id: uuid("id").primaryKey().defaultRandom(),
	// Stable id generated by the app (identifierForVendor or Keychain UUID);
	// also used as the RevenueCat app_user_id and StoreKit appAccountToken.
	installId: text("install_id").notNull().unique(),
	platform: text("platform").notNull().default("ios"),
	appVersion: text("app_version"),
	premiumUntil: timestamp("premium_until", { withTimezone: true }),
	premiumSource: text("premium_source"),
	freeUntil: timestamp("free_until", { withTimezone: true }),
	banned: boolean("banned").notNull().default(false),
	lastSeenAt: timestamp("last_seen_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
})

// One VLESS client per (device, server), created on the node on first connect
export const deviceClients = pgTable(
	"device_clients",
	{
		deviceId: uuid("device_id")
			.notNull()
			.references(() => devices.id, { onDelete: "cascade" }),
		serverId: uuid("server_id")
			.notNull()
			.references(() => servers.id, { onDelete: "cascade" }),
		clientUuid: uuid("client_uuid").notNull(),
		// This device's personal address in the server's IPv6 prefix
		ipv6Address: text("ipv6_address"),
		ipv6Rotations: integer("ipv6_rotations").notNull().default(0),
		ipv6RotatedAt: timestamp("ipv6_rotated_at", { withTimezone: true }),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},
	(t) => [primaryKey({ columns: [t.deviceId, t.serverId] })],
)

export const billingEvents = pgTable("billing_events", {
	id: uuid("id").primaryKey().defaultRandom(),
	provider: text("provider").notNull(),
	type: text("type").notNull(),
	installId: text("install_id"),
	payload: jsonb("payload").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
})

export const adRewards = pgTable("ad_rewards", {
	// AdMob transaction_id; primary key makes reward callbacks idempotent
	transactionId: text("transaction_id").primaryKey(),
	installId: text("install_id").notNull(),
	minutes: integer("minutes").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
})

export const settings = pgTable("settings", {
	key: text("key").primaryKey(),
	value: jsonb("value").notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
})

export type Server = typeof servers.$inferSelect
export type NewServer = typeof servers.$inferInsert
export type Device = typeof devices.$inferSelect
